// This file is auto-generated by @hey-api/openapi-ts

export const AnosDisponiveisPublicSchema = {
    properties: {
        anos: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Anos'
        }
    },
    type: 'object',
    required: ['anos'],
    title: 'AnosDisponiveisPublic',
    description: `Resposta de GET /vendas/livro/anos-disponiveis -- até os 5 anos
mais recentes com ao menos 1 venda (data_venda), em ordem
decrescente. Usado pra montar os botões da linha 'Ano' do menu
interativo -- se houver um 6º ano de histórico ele simplesmente
não aparece aqui (mas continua acessível via escopo 'todos_anos',
que não depende desta lista).`
} as const;

export const BairroPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'BairroPublic'
} as const;

export const BairrosPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BairroPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BairrosPublic'
} as const;

export const BlocoValeCreateSchema = {
    properties: {
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        primeira_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Ultima Folha'
        }
    },
    type: 'object',
    required: ['motorista_id', 'primeira_folha', 'ultima_folha'],
    title: 'BlocoValeCreate',
    description: `Corpo de POST /blocos-vale/ -- cria o bloco E já atribui o
motorista na mesma chamada (motorista é fixo desde a criação,
decisão confirmada -- não existe endpoint pra reatribuir depois).
Gera automaticamente uma linha Vale pra cada número entre
primeira_folha e ultima_folha (inclusive).`
} as const;

export const BlocoValePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        primeira_folha: {
            type: 'integer',
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            title: 'Ultima Folha'
        },
        total_vales: {
            type: 'integer',
            title: 'Total Vales'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'motorista_id', 'motorista_nome', 'primeira_folha', 'ultima_folha', 'total_vales', 'created_at'],
    title: 'BlocoValePublic'
} as const;

export const BlocosValePublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BlocoValePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BlocosValePublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ClienteCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        cpf: {
            type: 'string',
            maxLength: 14,
            minLength: 11,
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoCreate'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['nome', 'cpf'],
    title: 'ClienteCreate',
    description: `Corpo de POST /clientes/ -- cria cliente (+ endereço, se
informado) numa única chamada.

endereco é OPCIONAL no backend de propósito: a tela /clientes
exige endereço (validação no frontend daquela tela), mas a tela de
Venda (cadastro rápido de cliente no balcão) não -- o cliente pode
ser cadastrado só com nome/cpf/telefone e ganhar um endereço depois.`
} as const;

export const ClientePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        cpf: {
            type: 'string',
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'nome', 'cpf', 'created_at'],
    title: 'ClientePublic'
} as const;

export const ClienteUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        cpf: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14,
                    minLength: 11
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        }
    },
    type: 'object',
    title: 'ClienteUpdate',
    description: `Edição só dos dados do próprio cliente (nome/cpf/telefone).
Trocar de endereço é um endpoint separado (POST
/clientes/{id}/endereco), porque isso precisa fechar o histórico,
não é um UPDATE simples.`
} as const;

export const ClientesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientesPublic'
} as const;

export const EnderecoCreateSchema = {
    properties: {
        bairro_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bairro Id'
        },
        rua_nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Rua Nome'
        },
        numero: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Numero'
        },
        complemento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Complemento'
        }
    },
    type: 'object',
    required: ['bairro_id', 'rua_nome', 'numero'],
    title: 'EnderecoCreate',
    description: `Corpo usado para criar (ou trocar) o endereço de um cliente.

rua_nome é sempre texto livre, nunca um rua_id -- o endpoint
resolve pra uma Rua existente (case-insensitive, mesmo bairro) ou
cria uma nova na hora ("cresce por uso"). Isso evita o frontend
precisar gerenciar o caso "rua não existe ainda no catálogo".`
} as const;

export const EnderecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        numero: {
            type: 'string',
            title: 'Numero'
        },
        complemento: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Complemento'
        },
        rua_nome: {
            type: 'string',
            title: 'Rua Nome'
        },
        bairro_nome: {
            type: 'string',
            title: 'Bairro Nome'
        },
        cidade_nome: {
            type: 'string',
            title: 'Cidade Nome'
        }
    },
    type: 'object',
    required: ['id', 'numero', 'rua_nome', 'bairro_nome', 'cidade_nome'],
    title: 'EnderecoPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LivroVendasBucketSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        }
    },
    type: 'object',
    required: ['label', 'valor'],
    title: 'LivroVendasBucket',
    description: `Um ponto (barra) do gráfico -- label já formatado pro eixo X
(ex: 'Jan', '2025', 'Domingo', '01/08–02/08', dependendo da
granularidade ativa) e o valor em caixa (soma de valor_pago das
vendas já pagas) somado dentro daquele bucket de tempo.`
} as const;

export const LivroVendasFormaPagamentoValorSchema = {
    properties: {
        forma_pagamento: {
            type: 'string',
            title: 'Forma Pagamento'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        }
    },
    type: 'object',
    required: ['forma_pagamento', 'valor'],
    title: 'LivroVendasFormaPagamentoValor',
    description: `Uma linha do detalhamento de 'Em caixa' por forma de pagamento
-- forma_pagamento é o slug técnico (cartao/pix/dinheiro/vale, o
mesmo valor gravado em Venda.forma_pagamento); o label de exibição
é responsabilidade do frontend. valor é a soma de valor_pago das
vendas JÁ PAGAS daquela forma, dentro do período ativo.`
} as const;

export const LivroVendasListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VendaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        soma_preco: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Soma Preco'
        },
        soma_valor_pago: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Soma Valor Pago'
        }
    },
    type: 'object',
    required: ['data', 'count', 'soma_preco', 'soma_valor_pago'],
    title: 'LivroVendasListPublic',
    description: `Resposta de GET /vendas/livro (a tabela) -- diferente de
VendasPublic genérico porque inclui soma_preco/soma_valor_pago:
o total das colunas 'Preço' (valor_total) e 'Valor pago'
(valor_pago) de TODAS as vendas que batem com o filtro de data
ativo (data_inicio/data_fim), não só as da página atual -- é o
valor exibido na linha de totais no rodapé da tabela, que muda
dinamicamente junto com o filtro 'Consulta vendas data'.`
} as const;

export const LivroVendasResumoPublicSchema = {
    properties: {
        em_caixa_qtd: {
            type: 'integer',
            title: 'Em Caixa Qtd'
        },
        em_caixa_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Caixa Valor'
        },
        em_caixa_por_forma_pagamento: {
            items: {
                '$ref': '#/components/schemas/LivroVendasFormaPagamentoValor'
            },
            type: 'array',
            title: 'Em Caixa Por Forma Pagamento'
        },
        em_aberto_qtd: {
            type: 'integer',
            title: 'Em Aberto Qtd'
        },
        em_aberto_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Aberto Valor'
        },
        periodo_inicio: {
            type: 'string',
            format: 'date',
            title: 'Periodo Inicio'
        },
        periodo_fim: {
            type: 'string',
            format: 'date',
            title: 'Periodo Fim'
        },
        grafico: {
            items: {
                '$ref': '#/components/schemas/LivroVendasBucket'
            },
            type: 'array',
            title: 'Grafico'
        }
    },
    type: 'object',
    required: ['em_caixa_qtd', 'em_caixa_valor', 'em_caixa_por_forma_pagamento', 'em_aberto_qtd', 'em_aberto_valor', 'periodo_inicio', 'periodo_fim', 'grafico'],
    title: 'LivroVendasResumoPublic',
    description: `Resposta de GET /vendas/livro/resumo -- os 2 cards ('Em caixa'
e 'Em aberto') + o período textual + os pontos do gráfico, tudo
já filtrado pelo escopo ativo do menu interativo (ano/mês/semana).

em_caixa: vendas já pagas (pago_em preenchido) com data_venda
dentro do período -- qtd e soma de valor_pago (o que de fato
entrou no caixa).

em_caixa_por_forma_pagamento: o mesmo total de em_caixa_valor,
detalhado por forma de pagamento (cartao/pix/dinheiro/vale) --
sempre as 4 formas presentes na lista, mesmo com valor 0, nessa
ordem fixa (pedido do Ricardo). A soma dos 4 valores sempre bate
com em_caixa_valor.

em_aberto: vendas ainda não pagas (pago_em nulo -- sempre vale em
aberto ou em atraso) com data_venda dentro do período -- qtd e
soma de valor_total (o que falta receber).

periodo_inicio/periodo_fim: limites do período correspondente ao
escopo ativo, pro frontend montar o label '(dd/mm/aaaa -
dd/mm/aaaa)'.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModulePermissionSchema = {
    properties: {
        module: {
            type: 'string',
            title: 'Module'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create'
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read'
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update'
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete'
        }
    },
    type: 'object',
    required: ['module', 'can_create', 'can_read', 'can_update', 'can_delete'],
    title: 'ModulePermission',
    description: 'Permissão efetiva de um usuário em um módulo específico (CRUD).'
} as const;

export const ModulePermissionMatrixSchema = {
    properties: {
        module: {
            '$ref': '#/components/schemas/ModulePublic'
        },
        entries: {
            items: {
                '$ref': '#/components/schemas/RolePermissionEntry'
            },
            type: 'array',
            title: 'Entries'
        }
    },
    type: 'object',
    required: ['module', 'entries'],
    title: 'ModulePermissionMatrix'
} as const;

export const ModulePermissionMatrixUpdateSchema = {
    properties: {
        entries: {
            items: {
                '$ref': '#/components/schemas/RolePermissionUpdate'
            },
            type: 'array',
            title: 'Entries'
        }
    },
    type: 'object',
    required: ['entries'],
    title: 'ModulePermissionMatrixUpdate',
    description: `Corpo de PUT /modules/{module_id}/permissions -- grava a
matriz inteira do módulo de uma vez (upsert por role).`
} as const;

export const ModulePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ModulePublic'
} as const;

export const ModuleUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ModuleUpdate',
    description: `Corpo de PATCH /modules/{module_id} -- edita SÓ label e/ou
description (campos cosméticos). \`name\` (o slug técnico) nunca é
editável por aqui de propósito -- ver comentário na classe Module.`
} as const;

export const ModulesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ModulePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ModulesPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrecoCreateSchema = {
    properties: {
        valor: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor'
        }
    },
    type: 'object',
    required: ['valor'],
    title: 'PrecoCreate',
    description: `Corpo de POST /produtos/{produto_id}/preco -- cadastra um novo
preço vigente pro produto (fecha o anterior automaticamente).`
} as const;

export const PrecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        valid_from: {
            type: 'string',
            format: 'date-time',
            title: 'Valid From'
        }
    },
    type: 'object',
    required: ['id', 'valor', 'valid_from'],
    title: 'PrecoPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProdutoComPrecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        preco_atual: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Atual'
        },
        preco_valid_from: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Valid From'
        }
    },
    type: 'object',
    required: ['id', 'title'],
    title: 'ProdutoComPrecoPublic',
    description: `Produto + preço vigente -- usado pela tela 'Cadastro de
Preços', que é 'parecida com Produto' só que atribuindo preço.`
} as const;

export const ProdutosComPrecoPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProdutoComPrecoPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ProdutosComPrecoPublic'
} as const;

export const ProximoValeNumeroPublicSchema = {
    properties: {
        numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Numero'
        }
    },
    type: 'object',
    title: 'ProximoValeNumeroPublic',
    description: `Resposta de GET /vendas/proximo-numero-vale/{motorista_id} --
sugestão do próximo número de vale livre dentro do(s) bloco(s)
atribuído(s) a esse motorista (null se não houver nenhum livre ou
nenhum bloco atribuído). É só uma sugestão pro campo "número do
vale" na tela de venda -- continua editável, não é obrigatório
usar exatamente esse número.`
} as const;

export const ResumoRecebimentoValePublicSchema = {
    properties: {
        em_aberto_qtd: {
            type: 'integer',
            title: 'Em Aberto Qtd'
        },
        em_aberto_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Aberto Valor'
        },
        atraso_qtd: {
            type: 'integer',
            title: 'Atraso Qtd'
        },
        atraso_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Atraso Valor'
        },
        aguardando_baixa_qtd: {
            type: 'integer',
            title: 'Aguardando Baixa Qtd'
        },
        aguardando_baixa_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Aguardando Baixa Valor'
        },
        pagos_mes_qtd: {
            type: 'integer',
            title: 'Pagos Mes Qtd'
        },
        pagos_mes_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Pagos Mes Valor'
        }
    },
    type: 'object',
    required: ['em_aberto_qtd', 'em_aberto_valor', 'atraso_qtd', 'atraso_valor', 'aguardando_baixa_qtd', 'aguardando_baixa_valor', 'pagos_mes_qtd', 'pagos_mes_valor'],
    title: 'ResumoRecebimentoValePublic',
    description: `Resposta de GET /vendas/vales-recebimento/resumo -- os 4 cards
da tela de Recebimento de Vale.

em_aberto_valor / atraso_valor: soma do valor_total das vendas
naquele grupo (não desconta nada -- são vendas que ainda não
tiveram nenhum recebimento registrado).

aguardando_baixa_valor: soma do valor_pago (o que foi de fato
registrado como recebido, ainda não conferido/baixado na
distribuidora) -- não o valor_total, porque o que importa aqui pro
operador é quanto ele deve esperar receber/conferir em mãos.

pagos_mes_qtd / pagos_mes_valor: vendas em vale já BAIXADAS
(pago_em não nulo) cujo pago_em cai dentro do mês vigente (do dia
1 ao último dia do mês corrente) -- não é sobre quando a venda foi
feita, é sobre quando foi dada a baixa. pagos_mes_valor soma
valor_pago (o que de fato entrou no caixa naqueles vales).`
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate',
    description: `Corpo de POST /roles/ -- cria uma nova role RBAC (ex: 'gerente',
'motorista'). Nome deve ser único (validado no endpoint).`
} as const;

export const RolePermissionEntrySchema = {
    properties: {
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create'
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read'
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update'
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete'
        }
    },
    type: 'object',
    required: ['role_id', 'role_name', 'can_create', 'can_read', 'can_update', 'can_delete'],
    title: 'RolePermissionEntry',
    description: `Uma linha da matriz: o que uma role específica pode fazer no
módulo (zerado se ainda não houver RolePermission cadastrado).`
} as const;

export const RolePermissionUpdateSchema = {
    properties: {
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create',
            default: false
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read',
            default: false
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update',
            default: false
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete',
            default: false
        }
    },
    type: 'object',
    required: ['role_id'],
    title: 'RolePermissionUpdate'
} as const;

export const RolePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        user_count: {
            type: 'integer',
            title: 'User Count',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RolePublic',
    description: `Role RBAC exposta pra UI (não confundir com is_superuser).

user_count vem sempre calculado pelo endpoint (não é uma coluna do
banco) -- usado pela tela "Gerenciar Roles" pra avisar o superuser
quantos usuários seriam desvinculados antes de confirmar um DELETE
(a FK UserRole.role_id tem ondelete=CASCADE, então apagar a role
desvincula silenciosamente se a UI não avisar antes).`
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'RoleUpdate',
    description: `Corpo de PATCH /roles/{role_id} -- edição parcial (nome e/ou
descrição). Renomear uma role não quebra nada além do óbvio: as
permissões e vínculos de usuário são por role_id, não por nome.`
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RolesPublic'
} as const;

export const RuaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'RuaPublic'
} as const;

export const RuasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RuaPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RuasPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPermissionsSchema = {
    properties: {
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/ModulePermission'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['is_superuser', 'roles', 'permissions'],
    title: 'UserPermissions',
    description: 'Resposta completa de permissões do usuário logado.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserPublicWithRolesSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublicWithRoles',
    description: `UserPublic + nomes das roles RBAC atribuídas -- usado pela
tabela de Usuários na tela de admin, que mostra e permite editar
as roles de cada um.`
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRolesUpdateSchema = {
    properties: {
        role_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Role Ids'
        }
    },
    type: 'object',
    required: ['role_ids'],
    title: 'UserRolesUpdate',
    description: `Corpo de PUT /users/{user_id}/roles -- substitui o conjunto
inteiro de roles do usuário pelos ids informados (lista vazia
remove todas as roles).`
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicWithRolesSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublicWithRoles'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublicWithRoles'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VendaBaixarValeRequestSchema = {
    properties: {
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valor Pago'
        }
    },
    type: 'object',
    title: 'VendaBaixarValeRequest',
    description: `Corpo de PATCH /vendas/{id}/baixar-vale -- confirma
oficialmente o recebimento na distribuidora (sempre feito ali,
nunca em campo) e FECHA a venda de vez (pago_em), não importa o
valor. valor_pago é opcional: se omitido, usa o valor já
registrado por marcar-pago. Se for menor que valor_total, a
diferença é um desconto -- não deixa a venda em aberto de novo
(ver comentário em Venda, models.py).`
} as const;

export const VendaCreateSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        endereco_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endereco Id'
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        forma_pagamento: {
            type: 'string',
            enum: ['cartao', 'pix', 'dinheiro', 'vale'],
            title: 'Forma Pagamento'
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Pago'
        },
        data_venda: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Venda'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/VendaItemCreate'
            },
            type: 'array',
            minItems: 1,
            title: 'Itens'
        }
    },
    type: 'object',
    required: ['cliente_id', 'motorista_id', 'forma_pagamento', 'valor_pago', 'itens'],
    title: 'VendaCreate',
    description: `Corpo de POST /vendas/ -- cria a venda inteira (cabeçalho +
itens da sacola) numa única transação.

vale_numero é o número físico da folha do vale (não o vale_id) --
o endpoint resolve pra um Vale existente e valida que ainda não foi
usado em outra venda. data_pagamento_vale, se não informado e a
forma for 'vale', é calculado automaticamente como o 5º dia útil
do mês seguinte (decisão do Ricardo: dá previsibilidade ao cliente
alinhada com o pagamento do salário).`
} as const;

export const VendaItemCreateSchema = {
    properties: {
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        quantidade: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantidade'
        }
    },
    type: 'object',
    required: ['produto_id', 'quantidade'],
    title: 'VendaItemCreate'
} as const;

export const VendaItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        produto_title: {
            type: 'string',
            title: 'Produto Title'
        },
        quantidade: {
            type: 'integer',
            title: 'Quantidade'
        },
        preco_unitario: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Preco Unitario'
        },
        subtotal: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Subtotal'
        }
    },
    type: 'object',
    required: ['id', 'produto_id', 'produto_title', 'quantidade', 'preco_unitario', 'subtotal'],
    title: 'VendaItemPublic'
} as const;

export const VendaMarcarPagoRequestSchema = {
    properties: {
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Pago'
        }
    },
    type: 'object',
    required: ['valor_pago'],
    title: 'VendaMarcarPagoRequest',
    description: `Corpo de PATCH /vendas/{id}/marcar-pago -- registra que o
valor foi recebido (hoje: por um operador na tela de Recebimento
de Vale; no futuro: por um motorista numa interface própria em
campo). NÃO fecha a venda -- só a baixa (endpoint separado, só
na distribuidora) faz isso.`
} as const;

export const VendaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        forma_pagamento: {
            type: 'string',
            title: 'Forma Pagamento'
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        valor_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Total'
        },
        valor_pago: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Pago'
        },
        data_venda: {
            type: 'string',
            format: 'date',
            title: 'Data Venda'
        },
        pago_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pago Em'
        },
        recebido_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Em'
        },
        recebido_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Por Nome'
        },
        criado_por_id: {
            type: 'string',
            format: 'uuid',
            title: 'Criado Por Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/VendaItemPublic'
            },
            type: 'array',
            title: 'Itens',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'cliente_id', 'cliente_nome', 'motorista_id', 'motorista_nome', 'forma_pagamento', 'valor_total', 'valor_pago', 'data_venda', 'criado_por_id', 'created_at'],
    title: 'VendaPublic'
} as const;

export const VendasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VendaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'VendasPublic'
} as const;