// This file is auto-generated by @hey-api/openapi-ts

export const AnosDisponiveisPublicSchema = {
    properties: {
        anos: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Anos'
        }
    },
    type: 'object',
    required: ['anos'],
    title: 'AnosDisponiveisPublic'
} as const;

export const BairroPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'BairroPublic'
} as const;

export const BairrosPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BairroPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BairrosPublic'
} as const;

export const BlocoValeCreateSchema = {
    properties: {
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        primeira_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Ultima Folha'
        }
    },
    type: 'object',
    required: ['motorista_id', 'primeira_folha', 'ultima_folha'],
    title: 'BlocoValeCreate'
} as const;

export const BlocoValeGasCreateSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        primeira_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Ultima Folha'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['cliente_id', 'primeira_folha', 'ultima_folha', 'data'],
    title: 'BlocoValeGasCreate'
} as const;

export const BlocoValeGasPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        cliente_cpf: {
            type: 'string',
            title: 'Cliente Cpf'
        },
        primeira_folha: {
            type: 'integer',
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            title: 'Ultima Folha'
        },
        total_folhas: {
            type: 'integer',
            title: 'Total Folhas'
        },
        data: {
            type: 'string',
            format: 'date',
            title: 'Data'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'cliente_id', 'cliente_nome', 'cliente_cpf', 'primeira_folha', 'ultima_folha', 'total_folhas', 'data', 'created_at'],
    title: 'BlocoValeGasPublic'
} as const;

export const BlocoValePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        primeira_folha: {
            type: 'integer',
            title: 'Primeira Folha'
        },
        ultima_folha: {
            type: 'integer',
            title: 'Ultima Folha'
        },
        total_vales: {
            type: 'integer',
            title: 'Total Vales'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'motorista_id', 'motorista_nome', 'primeira_folha', 'ultima_folha', 'total_vales', 'created_at'],
    title: 'BlocoValePublic'
} as const;

export const BlocosValeGasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BlocoValeGasPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BlocosValeGasPublic'
} as const;

export const BlocosValePublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BlocoValePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'BlocosValePublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CascoItemCreateSchema = {
    properties: {
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        quantidade: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantidade'
        }
    },
    type: 'object',
    required: ['produto_id', 'quantidade'],
    title: 'CascoItemCreate'
} as const;

export const CascosClientePublicSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        total_cascos_abertos: {
            type: 'integer',
            title: 'Total Cascos Abertos'
        },
        cascos: {
            items: {
                '$ref': '#/components/schemas/EmprestimoCascoPublic'
            },
            type: 'array',
            title: 'Cascos'
        }
    },
    type: 'object',
    required: ['cliente_id', 'total_cascos_abertos', 'cascos'],
    title: 'CascosClientePublic'
} as const;

export const ClienteCreateSchema = {
    properties: {
        nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Nome'
        },
        cpf: {
            type: 'string',
            maxLength: 14,
            minLength: 11,
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoCreate'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['nome', 'cpf'],
    title: 'ClienteCreate'
} as const;

export const ClienteFiadoPublicSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        saldo: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Saldo'
        },
        tem_atraso: {
            type: 'boolean',
            title: 'Tem Atraso'
        },
        vence_breve: {
            type: 'boolean',
            title: 'Vence Breve'
        },
        data_vencimento_mais_antiga: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Vencimento Mais Antiga'
        }
    },
    type: 'object',
    required: ['cliente_id', 'cliente_nome', 'saldo', 'tem_atraso', 'vence_breve'],
    title: 'ClienteFiadoPublic',
    description: 'Resumo de fiado em aberto por cliente — retornado por GET /vendas/clientes-com-fiado.'
} as const;

export const ClientePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        },
        cpf: {
            type: 'string',
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'nome', 'cpf', 'created_at'],
    title: 'ClientePublic'
} as const;

export const ClienteUpdateSchema = {
    properties: {
        nome: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome'
        },
        cpf: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14,
                    minLength: 11
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpf'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        }
    },
    type: 'object',
    title: 'ClienteUpdate'
} as const;

export const ClientesFiadoPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClienteFiadoPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientesFiadoPublic'
} as const;

export const ClientesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientesPublic'
} as const;

export const DemandaVendaAceitarRequestSchema = {
    properties: {
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        }
    },
    type: 'object',
    title: 'DemandaVendaAceitarRequest'
} as const;

export const DemandaVendaCreateSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        endereco_id: {
            type: 'string',
            format: 'uuid',
            title: 'Endereco Id'
        },
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        },
        observacao: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/DemandaVendaItemCreate'
            },
            type: 'array',
            title: 'Itens',
            default: []
        }
    },
    type: 'object',
    required: ['cliente_id', 'endereco_id'],
    title: 'DemandaVendaCreate'
} as const;

export const DemandaVendaItemCreateSchema = {
    properties: {
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        quantidade: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantidade'
        }
    },
    type: 'object',
    required: ['produto_id', 'quantidade'],
    title: 'DemandaVendaItemCreate'
} as const;

export const DemandaVendaItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        produto_title: {
            type: 'string',
            title: 'Produto Title'
        },
        quantidade: {
            type: 'integer',
            title: 'Quantidade'
        }
    },
    type: 'object',
    required: ['id', 'produto_id', 'produto_title', 'quantidade'],
    title: 'DemandaVendaItemPublic'
} as const;

export const DemandaVendaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        endereco: {
            '$ref': '#/components/schemas/EnderecoPublic'
        },
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        },
        motorista_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Nome'
        },
        observacao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        criado_por_id: {
            type: 'string',
            format: 'uuid',
            title: 'Criado Por Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        respondida_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Respondida Em'
        },
        finalizada_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finalizada Em'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/DemandaVendaItemPublic'
            },
            type: 'array',
            title: 'Itens',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'cliente_id', 'cliente_nome', 'endereco', 'status', 'criado_por_id', 'created_at'],
    title: 'DemandaVendaPublic'
} as const;

export const DemandaVendaReatribuirRequestSchema = {
    properties: {
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        }
    },
    type: 'object',
    title: 'DemandaVendaReatribuirRequest'
} as const;

export const DemandasVendaPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DemandaVendaPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'DemandasVendaPublic'
} as const;

export const EmprestimoCascoConfirmarRequestSchema = {
    properties: {
        observacao: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        }
    },
    type: 'object',
    title: 'EmprestimoCascoConfirmarRequest'
} as const;

export const EmprestimoCascoDesfazerRequestSchema = {
    properties: {
        observacao: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        }
    },
    type: 'object',
    title: 'EmprestimoCascoDesfazerRequest'
} as const;

export const EmprestimoCascoLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        evento: {
            type: 'string',
            title: 'Evento'
        },
        usuario_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Usuario Nome'
        },
        observacao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'evento', 'created_at'],
    title: 'EmprestimoCascoLogPublic'
} as const;

export const EmprestimoCascoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        venda_id: {
            type: 'string',
            format: 'uuid',
            title: 'Venda Id'
        },
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        produto_nome: {
            type: 'string',
            title: 'Produto Nome'
        },
        quantidade: {
            type: 'integer',
            title: 'Quantidade'
        },
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        },
        motorista_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Nome'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        recebido_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Em'
        },
        recebido_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Por Nome'
        },
        confirmado_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confirmado Em'
        },
        confirmado_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confirmado Por Nome'
        },
        dias_em_aberto: {
            type: 'integer',
            title: 'Dias Em Aberto',
            default: 0
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        logs: {
            items: {
                '$ref': '#/components/schemas/EmprestimoCascoLogPublic'
            },
            type: 'array',
            title: 'Logs',
            default: []
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'venda_id', 'produto_id', 'produto_nome', 'quantidade', 'cliente_id', 'cliente_nome', 'status', 'created_at'],
    title: 'EmprestimoCascoPublic'
} as const;

export const EmprestimoCascoReceberRequestSchema = {
    properties: {
        observacao: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Observacao'
        }
    },
    type: 'object',
    title: 'EmprestimoCascoReceberRequest'
} as const;

export const EmprestimosCascoPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EmprestimoCascoPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        total_cascos_abertos: {
            type: 'integer',
            title: 'Total Cascos Abertos'
        }
    },
    type: 'object',
    required: ['data', 'count', 'total_cascos_abertos'],
    title: 'EmprestimosCascoPublic'
} as const;

export const EnderecoCreateSchema = {
    properties: {
        bairro_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bairro Id'
        },
        rua_nome: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Rua Nome'
        },
        numero: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Numero'
        },
        complemento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Complemento'
        }
    },
    type: 'object',
    required: ['bairro_id', 'rua_nome', 'numero'],
    title: 'EnderecoCreate'
} as const;

export const EnderecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        numero: {
            type: 'string',
            title: 'Numero'
        },
        complemento: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Complemento'
        },
        rua_nome: {
            type: 'string',
            title: 'Rua Nome'
        },
        bairro_nome: {
            type: 'string',
            title: 'Bairro Nome'
        },
        cidade_nome: {
            type: 'string',
            title: 'Cidade Nome'
        },
        latitude: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        }
    },
    type: 'object',
    required: ['id', 'numero', 'rua_nome', 'bairro_nome', 'cidade_nome'],
    title: 'EnderecoPublic'
} as const;

export const GasPovoRecebimentoPublicSchema = {
    properties: {
        pendentes: {
            items: {
                '$ref': '#/components/schemas/GasPovoVendaPublic'
            },
            type: 'array',
            title: 'Pendentes'
        },
        pendentes_qtd: {
            type: 'integer',
            title: 'Pendentes Qtd'
        },
        pendentes_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Pendentes Valor'
        },
        recebidos_mes_qtd: {
            type: 'integer',
            title: 'Recebidos Mes Qtd'
        },
        recebidos_mes_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Recebidos Mes Valor'
        }
    },
    type: 'object',
    required: ['pendentes', 'pendentes_qtd', 'pendentes_valor', 'recebidos_mes_qtd', 'recebidos_mes_valor'],
    title: 'GasPovoRecebimentoPublic'
} as const;

export const GasPovoVendaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        valor_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Total'
        },
        gas_povo_frete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Gas Povo Frete'
        },
        gas_povo_frete_recebido_em: {
            type: 'string',
            format: 'date-time',
            title: 'Gas Povo Frete Recebido Em'
        },
        data_venda: {
            type: 'string',
            format: 'date',
            title: 'Data Venda'
        },
        pago_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pago Em'
        },
        dias_em_aberto: {
            type: 'integer',
            title: 'Dias Em Aberto'
        }
    },
    type: 'object',
    required: ['id', 'cliente_id', 'cliente_nome', 'motorista_nome', 'valor_total', 'gas_povo_frete', 'gas_povo_frete_recebido_em', 'data_venda', 'dias_em_aberto'],
    title: 'GasPovoVendaPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InadimplentesMotoristaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'InadimplentesMotoristaPublic'
} as const;

export const InadimplentesMotoristasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InadimplentesMotoristaPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'InadimplentesMotoristasPublic'
} as const;

export const InadimplentesResumoPublicSchema = {
    properties: {
        qtd: {
            type: 'integer',
            title: 'Qtd'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        periodo_inicio: {
            type: 'string',
            format: 'date',
            title: 'Periodo Inicio'
        },
        periodo_fim: {
            type: 'string',
            format: 'date',
            title: 'Periodo Fim'
        },
        grafico: {
            items: {
                '$ref': '#/components/schemas/LivroVendasBucket'
            },
            type: 'array',
            title: 'Grafico'
        }
    },
    type: 'object',
    required: ['qtd', 'valor', 'periodo_inicio', 'periodo_fim', 'grafico'],
    title: 'InadimplentesResumoPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        vende_casco: {
            type: 'boolean',
            title: 'Vende Casco',
            default: false
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        vende_casco: {
            type: 'boolean',
            title: 'Vende Casco',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        vende_casco: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vende Casco'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LivroVendasBucketSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        }
    },
    type: 'object',
    required: ['label', 'valor'],
    title: 'LivroVendasBucket'
} as const;

export const LivroVendasFormaPagamentoValorSchema = {
    properties: {
        forma_pagamento: {
            type: 'string',
            title: 'Forma Pagamento'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        }
    },
    type: 'object',
    required: ['forma_pagamento', 'valor'],
    title: 'LivroVendasFormaPagamentoValor'
} as const;

export const LivroVendasListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VendaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        soma_preco: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Soma Preco'
        },
        soma_valor_pago: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Soma Valor Pago'
        }
    },
    type: 'object',
    required: ['data', 'count', 'soma_preco', 'soma_valor_pago'],
    title: 'LivroVendasListPublic'
} as const;

export const LivroVendasResumoPublicSchema = {
    properties: {
        em_caixa_qtd: {
            type: 'integer',
            title: 'Em Caixa Qtd'
        },
        em_caixa_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Caixa Valor'
        },
        em_caixa_por_forma_pagamento: {
            items: {
                '$ref': '#/components/schemas/LivroVendasFormaPagamentoValor'
            },
            type: 'array',
            title: 'Em Caixa Por Forma Pagamento'
        },
        em_aberto_qtd: {
            type: 'integer',
            title: 'Em Aberto Qtd'
        },
        em_aberto_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Aberto Valor'
        },
        periodo_inicio: {
            type: 'string',
            format: 'date',
            title: 'Periodo Inicio'
        },
        periodo_fim: {
            type: 'string',
            format: 'date',
            title: 'Periodo Fim'
        },
        grafico: {
            items: {
                '$ref': '#/components/schemas/LivroVendasBucket'
            },
            type: 'array',
            title: 'Grafico'
        }
    },
    type: 'object',
    required: ['em_caixa_qtd', 'em_caixa_valor', 'em_caixa_por_forma_pagamento', 'em_aberto_qtd', 'em_aberto_valor', 'periodo_inicio', 'periodo_fim', 'grafico'],
    title: 'LivroVendasResumoPublic'
} as const;

export const LogradouroReferenciaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'LogradouroReferenciaPublic'
} as const;

export const LogradourosReferenciaPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LogradouroReferenciaPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'LogradourosReferenciaPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModulePermissionSchema = {
    properties: {
        module: {
            type: 'string',
            title: 'Module'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create'
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read'
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update'
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete'
        }
    },
    type: 'object',
    required: ['module', 'can_create', 'can_read', 'can_update', 'can_delete'],
    title: 'ModulePermission'
} as const;

export const ModulePermissionMatrixSchema = {
    properties: {
        module: {
            '$ref': '#/components/schemas/ModulePublic'
        },
        entries: {
            items: {
                '$ref': '#/components/schemas/RolePermissionEntry'
            },
            type: 'array',
            title: 'Entries'
        }
    },
    type: 'object',
    required: ['module', 'entries'],
    title: 'ModulePermissionMatrix'
} as const;

export const ModulePermissionMatrixUpdateSchema = {
    properties: {
        entries: {
            items: {
                '$ref': '#/components/schemas/RolePermissionUpdate'
            },
            type: 'array',
            title: 'Entries'
        }
    },
    type: 'object',
    required: ['entries'],
    title: 'ModulePermissionMatrixUpdate'
} as const;

export const ModulePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ModulePublic'
} as const;

export const ModuleUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ModuleUpdate'
} as const;

export const ModulesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ModulePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ModulesPublic'
} as const;

export const MotoristaDisponibilidadePublicSchema = {
    properties: {
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        disponivel: {
            type: 'boolean',
            title: 'Disponivel'
        }
    },
    type: 'object',
    required: ['motorista_id', 'motorista_nome', 'disponivel'],
    title: 'MotoristaDisponibilidadePublic'
} as const;

export const MotoristaDisponibilidadeUpdateSchema = {
    properties: {
        disponivel: {
            type: 'boolean',
            title: 'Disponivel'
        }
    },
    type: 'object',
    required: ['disponivel'],
    title: 'MotoristaDisponibilidadeUpdate'
} as const;

export const MotoristaFcmTokenUpdateSchema = {
    properties: {
        fcm_token: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Fcm Token'
        }
    },
    type: 'object',
    required: ['fcm_token'],
    title: 'MotoristaFcmTokenUpdate'
} as const;

export const MotoristaLocalizacaoPublicSchema = {
    properties: {
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        latitude: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Latitude'
        },
        longitude: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Longitude'
        },
        atualizado_em: {
            type: 'string',
            format: 'date-time',
            title: 'Atualizado Em'
        }
    },
    type: 'object',
    required: ['motorista_id', 'motorista_nome', 'latitude', 'longitude', 'atualizado_em'],
    title: 'MotoristaLocalizacaoPublic'
} as const;

export const MotoristaLocalizacaoUpdateSchema = {
    properties: {
        latitude: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 90,
                    minimum: -90
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,6}0*$'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 180,
                    minimum: -180
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,6}0*$'
                }
            ],
            title: 'Longitude'
        }
    },
    type: 'object',
    required: ['latitude', 'longitude'],
    title: 'MotoristaLocalizacaoUpdate'
} as const;

export const MotoristasDisponibilidadePublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MotoristaDisponibilidadePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MotoristasDisponibilidadePublic'
} as const;

export const MotoristasLocalizacaoPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MotoristaLocalizacaoPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MotoristasLocalizacaoPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrecoCreateSchema = {
    properties: {
        valor: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor'
        },
        preco_casco: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Casco'
        }
    },
    type: 'object',
    required: ['valor'],
    title: 'PrecoCreate'
} as const;

export const PrecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        preco_casco: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Casco'
        },
        valid_from: {
            type: 'string',
            format: 'date-time',
            title: 'Valid From'
        }
    },
    type: 'object',
    required: ['id', 'valor', 'valid_from'],
    title: 'PrecoPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProdutoComPrecoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        vende_casco: {
            type: 'boolean',
            title: 'Vende Casco',
            default: false
        },
        preco_atual: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Atual'
        },
        preco_casco_atual: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Casco Atual'
        },
        preco_valid_from: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Valid From'
        }
    },
    type: 'object',
    required: ['id', 'title'],
    title: 'ProdutoComPrecoPublic'
} as const;

export const ProdutosComPrecoPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProdutoComPrecoPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ProdutosComPrecoPublic'
} as const;

export const ProximoValeNumeroPublicSchema = {
    properties: {
        numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Numero'
        }
    },
    type: 'object',
    title: 'ProximoValeNumeroPublic'
} as const;

export const RankingMotoristaPublicSchema = {
    properties: {
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        quantidade: {
            type: 'integer',
            title: 'Quantidade'
        }
    },
    type: 'object',
    required: ['motorista_id', 'motorista_nome', 'quantidade'],
    title: 'RankingMotoristaPublic'
} as const;

export const RankingSemanaPublicSchema = {
    properties: {
        periodo_inicio: {
            type: 'string',
            format: 'date',
            title: 'Periodo Inicio'
        },
        periodo_fim: {
            type: 'string',
            format: 'date',
            title: 'Periodo Fim'
        },
        motoristas: {
            items: {
                '$ref': '#/components/schemas/RankingMotoristaPublic'
            },
            type: 'array',
            title: 'Motoristas'
        }
    },
    type: 'object',
    required: ['periodo_inicio', 'periodo_fim', 'motoristas'],
    title: 'RankingSemanaPublic'
} as const;

export const ResumoRecebimentoValePublicSchema = {
    properties: {
        em_aberto_qtd: {
            type: 'integer',
            title: 'Em Aberto Qtd'
        },
        em_aberto_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Aberto Valor'
        },
        atraso_qtd: {
            type: 'integer',
            title: 'Atraso Qtd'
        },
        atraso_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Atraso Valor'
        },
        aguardando_baixa_qtd: {
            type: 'integer',
            title: 'Aguardando Baixa Qtd'
        },
        aguardando_baixa_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Aguardando Baixa Valor'
        },
        pagos_mes_qtd: {
            type: 'integer',
            title: 'Pagos Mes Qtd'
        },
        pagos_mes_valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Pagos Mes Valor'
        }
    },
    type: 'object',
    required: ['em_aberto_qtd', 'em_aberto_valor', 'atraso_qtd', 'atraso_valor', 'aguardando_baixa_qtd', 'aguardando_baixa_valor', 'pagos_mes_qtd', 'pagos_mes_valor'],
    title: 'ResumoRecebimentoValePublic'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RolePermissionEntrySchema = {
    properties: {
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create'
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read'
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update'
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete'
        }
    },
    type: 'object',
    required: ['role_id', 'role_name', 'can_create', 'can_read', 'can_update', 'can_delete'],
    title: 'RolePermissionEntry'
} as const;

export const RolePermissionUpdateSchema = {
    properties: {
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        can_create: {
            type: 'boolean',
            title: 'Can Create',
            default: false
        },
        can_read: {
            type: 'boolean',
            title: 'Can Read',
            default: false
        },
        can_update: {
            type: 'boolean',
            title: 'Can Update',
            default: false
        },
        can_delete: {
            type: 'boolean',
            title: 'Can Delete',
            default: false
        }
    },
    type: 'object',
    required: ['role_id'],
    title: 'RolePermissionUpdate'
} as const;

export const RolePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        user_count: {
            type: 'integer',
            title: 'User Count',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RolePublic'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const RolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RolePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RolesPublic'
} as const;

export const RuaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        nome: {
            type: 'string',
            title: 'Nome'
        }
    },
    type: 'object',
    required: ['id', 'nome'],
    title: 'RuaPublic'
} as const;

export const RuasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RuaPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'RuasPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPermissionsSchema = {
    properties: {
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/ModulePermission'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['is_superuser', 'roles', 'permissions'],
    title: 'UserPermissions'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserPublicWithRolesSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublicWithRoles'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRolesUpdateSchema = {
    properties: {
        role_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Role Ids'
        }
    },
    type: 'object',
    required: ['role_ids'],
    title: 'UserRolesUpdate'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicWithRolesSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublicWithRoles'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublicWithRoles'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VendaBaixarValeRequestSchema = {
    properties: {
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valor Pago'
        }
    },
    type: 'object',
    title: 'VendaBaixarValeRequest'
} as const;

export const VendaCreateSchema = {
    properties: {
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        endereco_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Endereco Id'
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        forma_pagamento: {
            type: 'string',
            enum: ['cartao_debito', 'cartao_credito', 'pix', 'dinheiro', 'vale', 'vale_gas', 'gas_povo'],
            title: 'Forma Pagamento'
        },
        pagamentos: {
            items: {
                '$ref': '#/components/schemas/VendaPagamentoCreate'
            },
            type: 'array',
            title: 'Pagamentos'
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        vale_gas_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Numero'
        },
        vale_gas_bloco_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Bloco Id'
        },
        gas_povo_frete: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete'
        },
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Pago'
        },
        data_venda: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Venda'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/VendaItemCreate'
            },
            type: 'array',
            minItems: 1,
            title: 'Itens'
        },
        cascos: {
            items: {
                '$ref': '#/components/schemas/CascoItemCreate'
            },
            type: 'array',
            title: 'Cascos'
        }
    },
    type: 'object',
    required: ['cliente_id', 'motorista_id', 'forma_pagamento', 'valor_pago', 'itens'],
    title: 'VendaCreate'
} as const;

export const VendaEditarRequestSchema = {
    properties: {
        forma_pagamento: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forma Pagamento'
        },
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valor Pago'
        },
        data_venda: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Venda'
        },
        motorista_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motorista Id'
        }
    },
    type: 'object',
    title: 'VendaEditarRequest'
} as const;

export const VendaEstornarRequestSchema = {
    properties: {
        valor_estorno: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Estorno'
        }
    },
    type: 'object',
    required: ['valor_estorno'],
    title: 'VendaEstornarRequest'
} as const;

export const VendaItemCreateSchema = {
    properties: {
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        quantidade: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Quantidade'
        },
        com_casco: {
            type: 'boolean',
            title: 'Com Casco',
            default: false
        }
    },
    type: 'object',
    required: ['produto_id', 'quantidade'],
    title: 'VendaItemCreate'
} as const;

export const VendaItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        produto_id: {
            type: 'string',
            format: 'uuid',
            title: 'Produto Id'
        },
        produto_title: {
            type: 'string',
            title: 'Produto Title'
        },
        quantidade: {
            type: 'integer',
            title: 'Quantidade'
        },
        preco_unitario: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Preco Unitario'
        },
        subtotal: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Subtotal'
        },
        com_casco: {
            type: 'boolean',
            title: 'Com Casco',
            default: false
        },
        preco_casco_snapshot: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preco Casco Snapshot'
        }
    },
    type: 'object',
    required: ['id', 'produto_id', 'produto_title', 'quantidade', 'preco_unitario', 'subtotal'],
    title: 'VendaItemPublic'
} as const;

export const VendaLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        campo: {
            type: 'string',
            title: 'Campo'
        },
        valor_anterior: {
            type: 'string',
            title: 'Valor Anterior'
        },
        valor_novo: {
            type: 'string',
            title: 'Valor Novo'
        },
        editado_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Editado Por Nome'
        },
        editado_em: {
            type: 'string',
            format: 'date-time',
            title: 'Editado Em'
        }
    },
    type: 'object',
    required: ['id', 'campo', 'valor_anterior', 'valor_novo', 'editado_em'],
    title: 'VendaLogPublic'
} as const;

export const VendaMarcarPagoRequestSchema = {
    properties: {
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Pago'
        }
    },
    type: 'object',
    required: ['valor_pago'],
    title: 'VendaMarcarPagoRequest'
} as const;

export const VendaPagamentoBaixarRequestSchema = {
    properties: {
        valor_pago: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Pago'
        }
    },
    type: 'object',
    required: ['valor_pago'],
    title: 'VendaPagamentoBaixarRequest'
} as const;

export const VendaPagamentoCreateSchema = {
    properties: {
        forma_pagamento: {
            type: 'string',
            enum: ['cartao_debito', 'cartao_credito', 'pix', 'dinheiro', 'vale', 'vale_gas', 'gas_povo'],
            title: 'Forma Pagamento'
        },
        valor: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor'
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        vale_gas_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Numero'
        },
        vale_gas_bloco_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Bloco Id'
        },
        gas_povo_frete: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete'
        }
    },
    type: 'object',
    required: ['forma_pagamento', 'valor'],
    title: 'VendaPagamentoCreate'
} as const;

export const VendaPagamentoEstornarRequestSchema = {
    properties: {
        valor_estorno: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d{0,2}0*$'
                }
            ],
            title: 'Valor Estorno'
        }
    },
    type: 'object',
    required: ['valor_estorno'],
    title: 'VendaPagamentoEstornarRequest'
} as const;

export const VendaPagamentoPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        forma_pagamento: {
            type: 'string',
            title: 'Forma Pagamento'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        valor_pago: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Pago',
            default: '0'
        },
        pago_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pago Em'
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        vale_gas_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Numero'
        },
        vale_gas_estabelecimento: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Estabelecimento'
        },
        gas_povo_frete: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete'
        },
        gas_povo_frete_recebido_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete Recebido Em'
        }
    },
    type: 'object',
    required: ['id', 'forma_pagamento', 'valor'],
    title: 'VendaPagamentoPublic'
} as const;

export const VendaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        cliente_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cliente Id'
        },
        cliente_nome: {
            type: 'string',
            title: 'Cliente Nome'
        },
        endereco: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EnderecoPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        motorista_id: {
            type: 'string',
            format: 'uuid',
            title: 'Motorista Id'
        },
        motorista_nome: {
            type: 'string',
            title: 'Motorista Nome'
        },
        forma_pagamento: {
            type: 'string',
            title: 'Forma Pagamento'
        },
        pagamentos: {
            items: {
                '$ref': '#/components/schemas/VendaPagamentoPublic'
            },
            type: 'array',
            title: 'Pagamentos',
            default: []
        },
        vale_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Numero'
        },
        data_pagamento_vale: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Pagamento Vale'
        },
        vale_gas_numero: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Numero'
        },
        vale_gas_estabelecimento: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vale Gas Estabelecimento'
        },
        gas_povo_frete: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete'
        },
        gas_povo_frete_recebido_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gas Povo Frete Recebido Em'
        },
        valor_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Total'
        },
        valor_pago: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor Pago'
        },
        data_venda: {
            type: 'string',
            format: 'date',
            title: 'Data Venda'
        },
        pago_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pago Em'
        },
        recebido_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Em'
        },
        recebido_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Recebido Por Nome'
        },
        status: {
            type: 'string',
            title: 'Status',
            default: 'ativa'
        },
        cancelada_em: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelada Em'
        },
        cancelada_por_nome: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelada Por Nome'
        },
        logs_edicao: {
            items: {
                '$ref': '#/components/schemas/VendaLogPublic'
            },
            type: 'array',
            title: 'Logs Edicao',
            default: []
        },
        qtd_edicoes: {
            type: 'integer',
            title: 'Qtd Edicoes',
            default: 0
        },
        criado_por_id: {
            type: 'string',
            format: 'uuid',
            title: 'Criado Por Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        itens: {
            items: {
                '$ref': '#/components/schemas/VendaItemPublic'
            },
            type: 'array',
            title: 'Itens',
            default: []
        },
        cascos_emprestados: {
            items: {
                '$ref': '#/components/schemas/EmprestimoCascoPublic'
            },
            type: 'array',
            title: 'Cascos Emprestados',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'cliente_id', 'cliente_nome', 'motorista_id', 'motorista_nome', 'forma_pagamento', 'valor_total', 'valor_pago', 'data_venda', 'criado_por_id', 'created_at'],
    title: 'VendaPublic'
} as const;

export const VendasPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VendaPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'VendasPublic'
} as const;