// [mcp-local harness] feature: gas-povo | plano: 9b775808 | 2026-09-06 00:15:12
// Patch types.gen.ts: gas_povo no Literal de VendaCreate e forma_pagamento, gas_povo_frete em VendaCreate e VendaPublic
// This file is auto-generated by @hey-api/openapi-ts

/**
 * Resposta de GET /vendas/livro/anos-disponiveis -- até os 5 anos
 * mais recentes com ao menos 1 venda (data_venda), em ordem
 * decrescente. Usado pra montar os botões da linha 'Ano' do menu
 * interativo -- se houver um 6º ano de histórico ele simplesmente
 * não aparece aqui (mas continua acessível via escopo 'todos_anos',
 * que não depende desta lista).
 *
 * Reaproveitado tal e qual por GET /vendas/inadimplentes/anos-
 * disponiveis (mesma forma: só uma lista de anos).
 */
export type AnosDisponiveisPublic = {
    anos: Array<(number)>;
};

export type BairroPublic = {
    id: string;
    nome: string;
};

export type BairrosPublic = {
    data: Array<BairroPublic>;
};

export type BlocosValePublic = {
    data: Array<BlocoValePublic>;
};

/**
 * Corpo de POST /blocos-vale/ -- cria o bloco E já atribui o
 * motorista na mesma chamada (motorista é fixo desde a criação,
 * decisão confirmada -- não existe endpoint pra reatribuir depois).
 * Gera automaticamente uma linha Vale pra cada número entre
 * primeira_folha e ultima_folha (inclusive).
 */
export type BlocoValeCreate = {
    motorista_id: string;
    primeira_folha: number;
    ultima_folha: number;
};

export type BlocoValePublic = {
    id: string;
    motorista_id: string;
    motorista_nome: string;
    primeira_folha: number;
    ultima_folha: number;
    total_vales: number;
    created_at: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Corpo de POST /clientes/ -- cria cliente (+ endereço, se
 * informado) numa única chamada.
 *
 * endereco é OPCIONAL no backend de propósito: a tela /clientes
 * exige endereço (validação no frontend daquela tela), mas a tela de
 * Venda (cadastro rápido de cliente no balcão) não -- o cliente pode
 * ser cadastrado só com nome/cpf/telefone e ganhar um endereço depois.
 */
export type ClienteCreate = {
    nome: string;
    cpf: string;
    telefone?: (string | null);
    endereco?: (EnderecoCreate | null);
};

export type ClientePublic = {
    id: string;
    nome: string;
    cpf: string;
    telefone?: (string | null);
    created_at: string;
    endereco?: (EnderecoPublic | null);
};

export type ClientesPublic = {
    data: Array<ClientePublic>;
    count: number;
};

/**
 * Edição só dos dados do próprio cliente (nome/cpf/telefone).
 * Trocar de endereço é um endpoint separado (POST
 * /clientes/{id}/endereco), porque isso precisa fechar o histórico,
 * não é um UPDATE simples.
 */
export type ClienteUpdate = {
    nome?: (string | null);
    cpf?: (string | null);
    telefone?: (string | null);
};

export type DemandasVendaPublic = {
    data: Array<DemandaVendaPublic>;
};

/**
 * Corpo de PATCH /demandas-venda/{id}/aceitar -- só precisa de
 * motorista_id quando o chamado está ABERTO (sem dono ainda); nesse
 * caso é obrigatório, é quem está "assumindo" o chamado. Se o
 * chamado já tinha um motorista definido na criação, motorista_id
 * aqui é ignorado (o dono já é fixo).
 */
export type DemandaVendaAceitarRequest = {
    motorista_id?: (string | null);
};

/**
 * Corpo de POST /demandas-venda/ -- despacha um chamado.
 * endereco_id é obrigatório e precisa apontar pra um Endereco já
 * cadastrado (do cliente ou outro) -- nunca texto livre.
 * motorista_id é opcional: se omitido, o chamado nasce ABERTO (pra
 * qualquer motorista aceitar); se informado, nasce já direcionado
 * pra aquele motorista específico. itens é opcional (pode ser um
 * chamado só com observação, ex: "cliente quer saber se tem gás").
 */
export type DemandaVendaCreate = {
    cliente_id: string;
    endereco_id: string;
    motorista_id?: (string | null);
    observacao?: (string | null);
    itens?: Array<DemandaVendaItemCreate>;
};

export type DemandaVendaItemCreate = {
    produto_id: string;
    quantidade: number;
};

export type DemandaVendaItemPublic = {
    id: string;
    produto_id: string;
    produto_title: string;
    quantidade: number;
};

export type DemandaVendaPublic = {
    id: string;
    cliente_id: string;
    cliente_nome: string;
    endereco: EnderecoPublic;
    motorista_id?: (string | null);
    motorista_nome?: (string | null);
    observacao?: (string | null);
    status: string;
    criado_por_id: string;
    created_at: string;
    respondida_em?: (string | null);
    finalizada_em?: (string | null);
    itens?: Array<DemandaVendaItemPublic>;
};

/**
 * Corpo de PATCH /demandas-venda/{id}/reatribuir -- SÓ o
 * atendente pode chamar (ação "Apagar" do módulo delegacao, ver
 * comentário de ciclo de vida acima da classe DemandaVenda).
 * motorista_id novo dono do chamado; None reabre como chamado
 * ABERTO (equivalente a "não era pra fulano, era pra qualquer um").
 * Só funciona a partir de status 'pendente' -- ver comentário
 * completo acima.
 */
export type DemandaVendaReatribuirRequest = {
    motorista_id?: (string | null);
};

/**
 * Corpo usado para criar (ou trocar) o endereço de um cliente.
 *
 * rua_nome é sempre texto livre, nunca um rua_id -- o endpoint
 * resolve pra uma Rua existente (case-insensitive, mesmo bairro) ou
 * cria uma nova na hora ("cresce por uso"). Isso evita o frontend
 * precisar gerenciar o caso "rua não existe ainda no catálogo".
 */
export type EnderecoCreate = {
    bairro_id: string;
    rua_nome: string;
    numero: string;
    complemento?: (string | null);
};

export type EnderecoPublic = {
    id: string;
    numero: string;
    complemento?: (string | null);
    rua_nome: string;
    bairro_nome: string;
    cidade_nome: string;
    latitude?: (string | null);
    longitude?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InadimplentesMotoristaPublic = {
    id: string;
    nome: string;
};

/**
 * Resposta de GET /vendas/inadimplentes/motoristas -- só os
 * motoristas que aparecem em ao menos 1 venda 'esteve em atraso'
 * (não a lista de usuários inteira), pra montar o dropdown "Nome
 * Motorista" -- "Todos Motoristas" (primeira opção) é sintético,
 * montado só no frontend, não vem daqui.
 */
export type InadimplentesMotoristasPublic = {
    data: Array<InadimplentesMotoristaPublic>;
};

/**
 * Resposta de GET /vendas/inadimplentes/resumo -- o único card
 * da tela ('Atraso maior que 30 dias') + o período textual + os
 * pontos do gráfico, filtrados pelo escopo ativo do menu
 * (todos_anos/ano/mes, agrupado por data_pagamento_vale).
 *
 * valor soma valor_total (o que ficou em aberto na época; para
 * quem já pagou depois, valor_total continua sendo o total original
 * da venda, não é afetado pelo pagamento).
 */
export type InadimplentesResumoPublic = {
    qtd: number;
    valor: string;
    periodo_inicio: string;
    periodo_fim: string;
    grafico: Array<LivroVendasBucket>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Um ponto (barra) do gráfico -- label já formatado pro eixo X
 * (ex: 'Jan', '2025', 'Domingo', '01/08–02/08', dependendo da
 * granularidade ativa) e o valor em caixa (soma de valor_pago das
 * vendas já pagas) somado dentro daquele bucket de tempo.
 */
export type LivroVendasBucket = {
    label: string;
    valor: string;
};

/**
 * Uma linha do detalhamento de 'Em caixa' por forma de pagamento
 * -- forma_pagamento é o slug técnico (cartao/pix/dinheiro/vale, o
 * mesmo valor gravado em Venda.forma_pagamento); o label de exibição
 * é responsabilidade do frontend. valor é a soma de valor_pago das
 * vendas JÁ PAGAS daquela forma, dentro do período ativo.
 */
export type LivroVendasFormaPagamentoValor = {
    forma_pagamento: string;
    valor: string;
};

/**
 * Resposta de GET /vendas/livro (a tabela) -- diferente de
 * VendasPublic genérico porque inclui soma_preco/soma_valor_pago:
 * o total das colunas 'Preço' (valor_total) e 'Valor pago'
 * (valor_pago) de TODAS as vendas que batem com o filtro de data
 * ativo (data_inicio/data_fim), não só as da página atual -- é o
 * valor exibido na linha de totais no rodapé da tabela, que muda
 * dinamicamente junto com o filtro 'Consulta vendas data'.
 *
 * Reaproveitado tal e qual por GET /vendas/inadimplentes (mesma
 * forma: data + count + soma_preco + soma_valor_pago) -- não faz
 * sentido duplicar o model só porque o nome da tela é outro.
 */
export type LivroVendasListPublic = {
    data: Array<VendaPublic>;
    count: number;
    soma_preco: string;
    soma_valor_pago: string;
};

/**
 * Resposta de GET /vendas/livro/resumo -- os 2 cards ('Em caixa'
 * e 'Em aberto') + o período textual + os pontos do gráfico, tudo
 * já filtrado pelo escopo ativo do menu interativo (ano/mês/semana).
 *
 * em_caixa: vendas já pagas (pago_em preenchido) com data_venda
 * dentro do período -- qtd e soma de valor_pago (o que de fato
 * entrou no caixa).
 *
 * em_caixa_por_forma_pagamento: o mesmo total de em_caixa_valor,
 * detalhado por forma de pagamento (cartao/pix/dinheiro/vale) --
 * sempre as 4 formas presentes na lista, mesmo com valor 0, nessa
 * ordem fixa (pedido do Ricardo). A soma dos 4 valores sempre bate
 * com em_caixa_valor.
 *
 * em_aberto: vendas ainda não pagas (pago_em nulo -- sempre vale em
 * aberto ou em atraso) com data_venda dentro do período -- qtd e
 * soma de valor_total (o que falta receber).
 *
 * periodo_inicio/periodo_fim: limites do período correspondente ao
 * escopo ativo, pro frontend montar o label '(dd/mm/aaaa -
 * dd/mm/aaaa)'.
 */
export type LivroVendasResumoPublic = {
    em_caixa_qtd: number;
    em_caixa_valor: string;
    em_caixa_por_forma_pagamento: Array<LivroVendasFormaPagamentoValor>;
    em_aberto_qtd: number;
    em_aberto_valor: string;
    periodo_inicio: string;
    periodo_fim: string;
    grafico: Array<LivroVendasBucket>;
};

export type LogradouroReferenciaPublic = {
    id: string;
    nome: string;
};

/**
 * Resposta de GET /bairros/logradouros-referencia -- a lista
 * inteira (hoje ~239 nomes), sem paginação nem busca no servidor,
 * já que o volume é pequeno. Usado no frontend como fonte extra de
 * sugestão no RuaAutocomplete, mesclado com as ruas já cadastradas
 * no bairro selecionado (ver comentário em LogradouroReferencia).
 */
export type LogradourosReferenciaPublic = {
    data: Array<LogradouroReferenciaPublic>;
};

export type Message = {
    message: string;
};

/**
 * Permissão efetiva de um usuário em um módulo específico (CRUD).
 */
export type ModulePermission = {
    module: string;
    description?: (string | null);
    can_create: boolean;
    can_read: boolean;
    can_update: boolean;
    can_delete: boolean;
};

export type ModulePermissionMatrix = {
    module: ModulePublic;
    entries: Array<RolePermissionEntry>;
};

/**
 * Corpo de PUT /modules/{module_id}/permissions -- grava a
 * matriz inteira do módulo de uma vez (upsert por role).
 */
export type ModulePermissionMatrixUpdate = {
    entries: Array<RolePermissionUpdate>;
};

export type ModulePublic = {
    id: string;
    name: string;
    description?: (string | null);
    label?: (string | null);
};

export type ModulesPublic = {
    data: Array<ModulePublic>;
};

/**
 * Corpo de PATCH /modules/{module_id} -- edita SÓ label e/ou
 * description (campos cosméticos). `name` (o slug técnico) nunca é
 * editável por aqui de propósito -- ver comentário na classe Module.
 */
export type ModuleUpdate = {
    label?: (string | null);
    description?: (string | null);
};

export type MotoristaDisponibilidadePublic = {
    motorista_id: string;
    motorista_nome: string;
    disponivel: boolean;
};

/**
 * Corpo de PUT /motoristas/{motorista_id}/disponibilidade --
 * chamado tanto pelo próprio motorista (toggle no app) quanto por
 * um gerente/atendente numa tela gerencial futura.
 */
export type MotoristaDisponibilidadeUpdate = {
    disponivel: boolean;
};

export type MotoristaLocalizacaoPublic = {
    motorista_id: string;
    motorista_nome: string;
    latitude: string;
    longitude: string;
    atualizado_em: string;
};

/**
 * Corpo de PUT /motoristas/{motorista_id}/localizacao -- upsert
 * de ping de localização (sobrescreve sempre, sem histórico).
 */
export type MotoristaLocalizacaoUpdate = {
    latitude: (number | string);
    longitude: (number | string);
};

/**
 * Resposta de GET /motoristas/disponibilidade -- todos os
 * usuários com role Motorista + seu status atual. Usado pra filtrar
 * o combo de despacho em /chamado (só disponíveis) e por uma futura
 * tela gerencial de disponibilidade.
 */
export type MotoristasDisponibilidadePublic = {
    data: Array<MotoristaDisponibilidadePublic>;
};

export type MotoristasLocalizacaoPublic = {
    data: Array<MotoristaLocalizacaoPublic>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Corpo de POST /produtos/{produto_id}/preco -- cadastra um novo
 * preço vigente pro produto (fecha o anterior automaticamente).
 */
export type PrecoCreate = {
    valor: (number | string);
};

export type PrecoPublic = {
    id: string;
    valor: string;
    valid_from: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Produto + preço vigente -- usado pela tela 'Cadastro de
 * Preços', que é 'parecida com Produto' só que atribuindo preço.
 */
export type ProdutoComPrecoPublic = {
    id: string;
    title: string;
    description?: (string | null);
    preco_atual?: (string | null);
    preco_valid_from?: (string | null);
};

export type ProdutosComPrecoPublic = {
    data: Array<ProdutoComPrecoPublic>;
};

/**
 * Resposta de GET /vendas/proximo-numero-vale/{motorista_id} --
 * sugestão do próximo número de vale livre dentro do(s) bloco(s)
 * atribuído(s) a esse motorista (null se não houver nenhum livre ou
 * nenhum bloco atribuído). É só uma sugestão pro campo "número do
 * vale" na tela de venda -- continua editável, não é obrigatório
 * usar exatamente esse número.
 */
export type ProximoValeNumeroPublic = {
    numero?: (number | null);
};

export type RankingMotoristaPublic = {
    motorista_id: string;
    motorista_nome: string;
    quantidade: number;
};

/**
 * Resposta de GET /vendas/ranking-semana -- top 3 motoristas por
 * QUANTIDADE de vendas na semana corrente (domingo-sábado, mesmo
 * corte de semana usado no Livro de Vendas -- ver _semana_atual em
 * vendas.py). Conta TODAS as vendas independente de forma de
 * pagamento ou status de pagamento -- é volume de atendimento, não
 * faturamento.
 */
export type RankingSemanaPublic = {
    periodo_inicio: string;
    periodo_fim: string;
    motoristas: Array<RankingMotoristaPublic>;
};

/**
 * Resposta de GET /vendas/vales-recebimento/resumo -- os 4 cards
 * da tela de Recebimento de Vale.
 *
 * em_aberto_valor / atraso_valor: soma do valor_total das vendas
 * naquele grupo (não desconta nada -- são vendas que ainda não
 * tiveram nenhum recebimento registrado).
 *
 * aguardando_baixa_valor: soma do valor_pago (o que foi de fato
 * registrado como recebido, ainda não conferido/baixado na
 * distribuidora) -- não o valor_total, porque o que importa aqui pro
 * operador é quanto ele deve esperar receber/conferir em mãos.
 *
 * pagos_mes_qtd / pagos_mes_valor: vendas em vale já BAIXADAS
 * (pago_em não nulo) cujo pago_em cai dentro do mês vigente (do dia
 * 1 ao último dia do mês corrente) -- não é sobre quando a venda foi
 * feita, é sobre quando foi dada a baixa. pagos_mes_valor soma
 * valor_pago (o que de fato entrou no caixa naqueles vales).
 */
export type ResumoRecebimentoValePublic = {
    em_aberto_qtd: number;
    em_aberto_valor: string;
    atraso_qtd: number;
    atraso_valor: string;
    aguardando_baixa_qtd: number;
    aguardando_baixa_valor: string;
    pagos_mes_qtd: number;
    pagos_mes_valor: string;
};

/**
 * Corpo de POST /roles/ -- cria uma nova role RBAC (ex: 'gerente',
 * 'motorista'). Nome deve ser único (validado no endpoint).
 */
export type RoleCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Uma linha da matriz: o que uma role específica pode fazer no
 * módulo (zerado se ainda não houver RolePermission cadastrado).
 */
export type RolePermissionEntry = {
    role_id: string;
    role_name: string;
    can_create: boolean;
    can_read: boolean;
    can_update: boolean;
    can_delete: boolean;
};

export type RolePermissionUpdate = {
    role_id: string;
    can_create?: boolean;
    can_read?: boolean;
    can_update?: boolean;
    can_delete?: boolean;
};

/**
 * Role RBAC exposta pra UI (não confundir com is_superuser).
 *
 * user_count vem sempre calculado pelo endpoint (não é uma coluna do
 * banco) -- usado pela tela "Gerenciar Roles" pra avisar o superuser
 * quantos usuários seriam desvinculados antes de confirmar um DELETE
 * (a FK UserRole.role_id tem ondelete=CASCADE, então apagar a role
 * desvincula silenciosamente se a UI não avisar antes).
 */
export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    user_count?: number;
};

export type RolesPublic = {
    data: Array<RolePublic>;
};

/**
 * Corpo de PATCH /roles/{role_id} -- edição parcial (nome e/ou
 * descrição). Renomear uma role não quebra nada além do óbvio: as
 * permissões e vínculos de usuário são por role_id, não por nome.
 */
export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type RuaPublic = {
    id: string;
    nome: string;
};

export type RuasPublic = {
    data: Array<RuaPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Resposta completa de permissões do usuário logado.
 */
export type UserPermissions = {
    is_superuser: boolean;
    roles: Array<(string)>;
    permissions: Array<ModulePermission>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * UserPublic + nomes das roles RBAC atribuídas -- usado pela
 * tabela de Usuários na tela de admin, que mostra e permite editar
 * as roles de cada um.
 */
export type UserPublicWithRoles = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Corpo de PUT /users/{user_id}/roles -- substitui o conjunto
 * inteiro de roles do usuário pelos ids informados (lista vazia
 * remove todas as roles).
 */
export type UserRolesUpdate = {
    role_ids: Array<(string)>;
};

export type UsersPublicWithRoles = {
    data: Array<UserPublicWithRoles>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Corpo de PATCH /vendas/{id}/baixar-vale -- confirma
 * oficialmente o recebimento na distribuidora (sempre feito ali,
 * nunca em campo) e FECHA a venda de vez (pago_em), não importa o
 * valor. valor_pago é opcional: se omitido, usa o valor já
 * registrado por marcar-pago. Se for menor que valor_total, a
 * diferença é um desconto -- não deixa a venda em aberto de novo
 * (ver comentário em Venda, models.py).
 */
export type VendaBaixarValeRequest = {
    valor_pago?: (number | string | null);
};

/**
 * Corpo de POST /vendas/ -- cria a venda inteira (cabeçalho +
 * itens da sacola) numa única transação.
 *
 * gas_povo_frete: frete cobrado do cliente no ato da entrega
 * (pago imediatamente). valor_pago para gas_povo = valor do governo
 * (a ser recebido depois via Recebimento Gas do Povo).
 */
export type VendaCreate = {
    cliente_id: string;
    endereco_id?: (string | null);
    motorista_id: string;
    forma_pagamento: 'cartao_debito' | 'cartao_credito' | 'pix' | 'dinheiro' | 'vale' | 'vale_gas' | 'gas_povo';
    vale_numero?: (number | null);
    data_pagamento_vale?: (string | null);
    vale_gas_numero?: (number | null);
    vale_gas_bloco_id?: (string | null);
    gas_povo_frete?: (number | string | null);
    valor_pago: (number | string);
    data_venda?: (string | null);
    itens: Array<VendaItemCreate>;
};

export type forma_pagamento = 'cartao_debito' | 'cartao_credito' | 'pix' | 'dinheiro' | 'vale' | 'vale_gas' | 'gas_povo';

export type VendaItemCreate = {
    produto_id: string;
    quantidade: number;
};

export type VendaItemPublic = {
    id: string;
    produto_id: string;
    produto_title: string;
    quantidade: number;
    preco_unitario: string;
    subtotal: string;
};

/**
 * Corpo de PATCH /vendas/{id}/marcar-pago -- registra que o
 * valor foi recebido (hoje: por um operador na tela de Recebimento
 * de Vale; no futuro: por um motorista numa interface própria em
 * campo). NÃO fecha a venda -- só a baixa (endpoint separado, só
 * na distribuidora) faz isso.
 */
export type VendaMarcarPagoRequest = {
    valor_pago: (number | string);
};

export type VendaPublic = {
    id: string;
    cliente_id: string;
    cliente_nome: string;
    endereco?: (EnderecoPublic | null);
    motorista_id: string;
    motorista_nome: string;
    forma_pagamento: string;
    vale_numero?: (number | null);
    data_pagamento_vale?: (string | null);
    gas_povo_frete?: (string | null);
    gas_povo_frete_recebido_em?: (string | null);
    valor_total: string;
    valor_pago: string;
    data_venda: string;
    pago_em?: (string | null);
    recebido_em?: (string | null);
    recebido_por_nome?: (string | null);
    criado_por_id: string;
    created_at: string;
    itens?: Array<VendaItemPublic>;
};

export type VendasPublic = {
    data: Array<VendaPublic>;
    count: number;
};

export type ClientesReadClientesData = {
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ClientesReadClientesResponse = (ClientesPublic);

export type ClientesCreateClienteData = {
    requestBody: ClienteCreate;
};

export type ClientesCreateClienteResponse = (ClientePublic);

export type ClientesReadClienteData = {
    id: string;
};

export type ClientesReadClienteResponse = (ClientePublic);

export type ClientesUpdateClienteData = {
    id: string;
    requestBody: ClienteUpdate;
};

export type ClientesUpdateClienteResponse = (ClientePublic);

export type ClientesTrocarEnderecoData = {
    id: string;
    requestBody: EnderecoCreate;
};

export type ClientesTrocarEnderecoResponse = (ClientePublic);

export type DelegacaoReadDemandasVendaData = {
    motoristaId?: (string | null);
    status?: ('pendente' | 'aceita' | 'recusada' | 'cancelada' | 'concluida' | null);
};

export type DelegacaoReadDemandasVendaResponse = (DemandasVendaPublic);

export type DelegacaoCreateDemandaVendaData = {
    requestBody: DemandaVendaCreate;
};

export type DelegacaoCreateDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoReadDemandasHojeResponse = (DemandasVendaPublic);

export type DelegacaoAceitarDemandaVendaData = {
    demandaId: string;
    requestBody?: DemandaVendaAceitarRequest;
};

export type DelegacaoAceitarDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoRecusarDemandaVendaData = {
    demandaId: string;
};

export type DelegacaoRecusarDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoCancelarDemandaVendaData = {
    demandaId: string;
};

export type DelegacaoCancelarDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoReatribuirDemandaVendaData = {
    demandaId: string;
    requestBody: DemandaVendaReatribuirRequest;
};

export type DelegacaoReatribuirDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoConcluirDemandaVendaData = {
    demandaId: string;
};

export type DelegacaoConcluirDemandaVendaResponse = (DemandaVendaPublic);

export type DelegacaoUpsertLocalizacaoMotoristaData = {
    motoristaId: string;
    requestBody: MotoristaLocalizacaoUpdate;
};

export type DelegacaoUpsertLocalizacaoMotoristaResponse = (MotoristaLocalizacaoPublic);

export type DelegacaoReadLocalizacoesMotoristasResponse = (MotoristasLocalizacaoPublic);

export type DelegacaoAtualizarDisponibilidadeMotoristaData = {
    motoristaId: string;
    requestBody: MotoristaDisponibilidadeUpdate;
};

export type DelegacaoAtualizarDisponibilidadeMotoristaResponse = (MotoristaDisponibilidadePublic);

export type DelegacaoReadDisponibilidadeMotoristasResponse = (MotoristasDisponibilidadePublic);

export type GeografiaReadBairrosResponse = (BairrosPublic);

export type GeografiaReadLogradourosReferenciaResponse = (LogradourosReferenciaPublic);

export type GeografiaReadRuasData = {
    bairroId: string;
};

export type GeografiaReadRuasResponse = (RuasPublic);

export type GeografiaGeocodificarEnderecoData = {
    enderecoId: string;
};

export type GeografiaGeocodificarEnderecoResponse = (EnderecoPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModulesReadModulesResponse = (ModulesPublic);

export type ModulesUpdateModuleData = {
    moduleId: string;
    requestBody: ModuleUpdate;
};

export type ModulesUpdateModuleResponse = (ModulePublic);

export type ModulesReadModulePermissionsData = {
    moduleId: string;
};

export type ModulesReadModulePermissionsResponse = (ModulePermissionMatrix);

export type ModulesUpdateModulePermissionsData = {
    moduleId: string;
    requestBody: ModulePermissionMatrixUpdate;
};

export type ModulesUpdateModulePermissionsResponse = (ModulePermissionMatrix);

export type PrecosReadPrecosResponse = (ProdutosComPrecoPublic);

export type PrecosSetPrecoData = {
    produtoId: string;
    requestBody: PrecoCreate;
};

export type PrecosSetPrecoResponse = (PrecoPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RolesReadRolesResponse = (RolesPublic);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RolePublic);

export type RolesUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RolesUpdateRoleResponse = (RolePublic);

export type RolesDeleteRoleData = {
    roleId: string;
};

export type RolesDeleteRoleResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublicWithRoles);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserPermissionsResponse = (UserPermissions);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersUpdateUserRolesData = {
    requestBody: UserRolesUpdate;
    userId: string;
};

export type UsersUpdateUserRolesResponse = (UserPublicWithRoles);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsRbacCheckData = {
    action: 'create' | 'read' | 'update' | 'delete';
    moduleName: string;
};

export type UtilsRbacCheckResponse = (Message);

export type ValesReadBlocosValeResponse = (BlocosValePublic);

export type ValesCreateBlocoValeData = {
    requestBody: BlocoValeCreate;
};

export type ValesCreateBlocoValeResponse = (BlocoValePublic);

export type VendasReadVendasData = {
    limit?: number;
    skip?: number;
};

export type VendasReadVendasResponse = (VendasPublic);

export type VendasCreateVendaData = {
    requestBody: VendaCreate;
};

export type VendasCreateVendaResponse = (VendaPublic);

export type VendasReadUltimoEnderecoClienteData = {
    clienteId: string;
};

export type VendasReadUltimoEnderecoClienteResponse = ((EnderecoPublic | null));

export type VendasReadHistoricoVendasClienteData = {
    clienteId: string;
    limit?: number;
};

export type VendasReadHistoricoVendasClienteResponse = (VendasPublic);

export type VendasReadProximoNumeroValeData = {
    motoristaId: string;
};

export type VendasReadProximoNumeroValeResponse = (ProximoValeNumeroPublic);

export type VendasReadResumoRecebimentoValeResponse = (ResumoRecebimentoValePublic);

export type VendasReadValesRecebimentoData = {
    buscaNumero?: (number | null);
    limit?: number;
    orderBy?: 'data_venda' | 'valor_total' | 'cliente';
    orderDir?: 'asc' | 'desc';
    skip?: number;
    status?: 'todos' | 'aguardando_baixa';
};

export type VendasReadValesRecebimentoResponse = (VendasPublic);

export type VendasMarcarVendaPagoData = {
    id: string;
    requestBody: VendaMarcarPagoRequest;
};

export type VendasMarcarVendaPagoResponse = (VendaPublic);

export type VendasBaixarValeData = {
    id: string;
    requestBody: VendaBaixarValeRequest;
};

export type VendasBaixarValeResponse = (VendaPublic);

export type VendasReadLivroAnosDisponiveisResponse = (AnosDisponiveisPublic);

export type VendasReadLivroResumoData = {
    ano?: (number | null);
    escopo?: 'todos_anos' | 'ano' | 'mes' | 'semana';
    mes?: (number | null);
};

export type VendasReadLivroResumoResponse = (LivroVendasResumoPublic);

export type VendasReadLivroVendasData = {
    dataFim?: (string | null);
    dataInicio?: (string | null);
    limit?: number;
    skip?: number;
    status?: 'todos' | 'pago' | 'em_aberto' | 'em_atraso';
};

export type VendasReadLivroVendasResponse = (LivroVendasListPublic);

export type VendasReadRankingSemanaResponse = (RankingSemanaPublic);

export type VendasReadInadimplentesAnosDisponiveisResponse = (AnosDisponiveisPublic);

export type VendasReadInadimplentesMotoristasResponse = (InadimplentesMotoristasPublic);

export type VendasReadInadimplentesResumoData = {
    ano?: (number | null);
    escopo?: 'todos_anos' | 'ano' | 'mes';
    mes?: (number | null);
};

export type VendasReadInadimplentesResumoResponse = (InadimplentesResumoPublic);

export type VendasReadInadimplentesData = {
    limit?: number;
    motoristaId?: (string | null);
    skip?: number;
};

export type VendasReadInadimplentesResponse = (LivroVendasListPublic);

export type VendasReadVendaData = {
    id: string;
};

export type VendasReadVendaResponse = (VendaPublic);
