// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Permissão efetiva de um usuário em um módulo específico (CRUD).
 */
export type ModulePermission = {
    module: string;
    description?: (string | null);
    can_create: boolean;
    can_read: boolean;
    can_update: boolean;
    can_delete: boolean;
};

export type ModulePermissionMatrix = {
    module: ModulePublic;
    entries: Array<RolePermissionEntry>;
};

/**
 * Corpo de PUT /modules/{module_id}/permissions -- grava a
 * matriz inteira do módulo de uma vez (upsert por role).
 */
export type ModulePermissionMatrixUpdate = {
    entries: Array<RolePermissionUpdate>;
};

export type ModulePublic = {
    id: string;
    name: string;
    description?: (string | null);
};

export type ModulesPublic = {
    data: Array<ModulePublic>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Uma linha da matriz: o que uma role específica pode fazer no
 * módulo (zerado se ainda não houver RolePermission cadastrado).
 */
export type RolePermissionEntry = {
    role_id: string;
    role_name: string;
    can_create: boolean;
    can_read: boolean;
    can_update: boolean;
    can_delete: boolean;
};

export type RolePermissionUpdate = {
    role_id: string;
    can_create?: boolean;
    can_read?: boolean;
    can_update?: boolean;
    can_delete?: boolean;
};

/**
 * Role RBAC exposta pra UI (não confundir com is_superuser).
 */
export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Resposta completa de permissões do usuário logado.
 */
export type UserPermissions = {
    is_superuser: boolean;
    roles: Array<(string)>;
    permissions: Array<ModulePermission>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * UserPublic + nomes das roles RBAC atribuídas -- usado pela
 * tabela de Usuários na tela de admin, que mostra e permite editar
 * as roles de cada um.
 */
export type UserPublicWithRoles = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Corpo de PUT /users/{user_id}/roles -- substitui o conjunto
 * inteiro de roles do usuário pelos ids informados (lista vazia
 * remove todas as roles).
 */
export type UserRolesUpdate = {
    role_ids: Array<(string)>;
};

export type UsersPublicWithRoles = {
    data: Array<UserPublicWithRoles>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModulesReadModulesResponse = (ModulesPublic);

export type ModulesReadModulePermissionsData = {
    moduleId: string;
};

export type ModulesReadModulePermissionsResponse = (ModulePermissionMatrix);

export type ModulesUpdateModulePermissionsData = {
    moduleId: string;
    requestBody: ModulePermissionMatrixUpdate;
};

export type ModulesUpdateModulePermissionsResponse = (ModulePermissionMatrix);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RolesReadRolesResponse = (RolesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublicWithRoles);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserPermissionsResponse = (UserPermissions);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersUpdateUserRolesData = {
    requestBody: UserRolesUpdate;
    userId: string;
};

export type UsersUpdateUserRolesResponse = (UserPublicWithRoles);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsRbacCheckData = {
    action: 'create' | 'read' | 'update' | 'delete';
    moduleName: string;
};

export type UtilsRbacCheckResponse = (Message);