/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupB2cDisabledRouteImport } from './routes/signup-b2c-disabled'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAberturaDiaRouteImport } from './routes/_layout/abertura-dia'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutChamadoRouteImport } from './routes/_layout/chamado'
import { Route as LayoutChamadosAtivosRouteImport } from './routes/_layout/chamados-ativos'
import { Route as LayoutClientesRouteImport } from './routes/_layout/clientes'
import { Route as LayoutDashboardSaldosRouteImport } from './routes/_layout/dashboard-saldos'
import { Route as LayoutFechamentoDiaRouteImport } from './routes/_layout/fechamento-dia'
import { Route as LayoutInadimplentesRouteImport } from './routes/_layout/inadimplentes'
import { Route as LayoutLivroVendasRouteImport } from './routes/_layout/livro-vendas'
import { Route as LayoutMapaRouteImport } from './routes/_layout/mapa'
import { Route as LayoutPermissionsRouteImport } from './routes/_layout/permissions'
import { Route as LayoutPrecosRouteImport } from './routes/_layout/precos'
import { Route as LayoutProdutosRouteImport } from './routes/_layout/produtos'
import { Route as LayoutRecebimentoGasPovoRouteImport } from './routes/_layout/recebimento-gas-povo'
import { Route as LayoutRecebimentoValeRouteImport } from './routes/_layout/recebimento-vale'
import { Route as LayoutRecebimentoValeGasRouteImport } from './routes/_layout/recebimento-vale-gas'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutValeGasRouteImport } from './routes/_layout/vale-gas'
import { Route as LayoutValesRouteImport } from './routes/_layout/vales'
import { Route as LayoutVendasRouteImport } from './routes/_layout/vendas'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupB2cDisabledRoute = SignupB2cDisabledRouteImport.update({
  id: '/signup-b2c-disabled',
  path: '/signup-b2c-disabled',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAberturaDiaRoute = LayoutAberturaDiaRouteImport.update({
  id: '/abertura-dia',
  path: '/abertura-dia',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChamadoRoute = LayoutChamadoRouteImport.update({
  id: '/chamado',
  path: '/chamado',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChamadosAtivosRoute = LayoutChamadosAtivosRouteImport.update({
  id: '/chamados-ativos',
  path: '/chamados-ativos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesRoute = LayoutClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardSaldosRoute = LayoutDashboardSaldosRouteImport.update({
  id: '/dashboard-saldos',
  path: '/dashboard-saldos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFechamentoDiaRoute = LayoutFechamentoDiaRouteImport.update({
  id: '/fechamento-dia',
  path: '/fechamento-dia',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInadimplentesRoute = LayoutInadimplentesRouteImport.update({
  id: '/inadimplentes',
  path: '/inadimplentes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLivroVendasRoute = LayoutLivroVendasRouteImport.update({
  id: '/livro-vendas',
  path: '/livro-vendas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMapaRoute = LayoutMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPermissionsRoute = LayoutPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrecosRoute = LayoutPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProdutosRoute = LayoutProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecebimentoGasPovoRoute =
  LayoutRecebimentoGasPovoRouteImport.update({
    id: '/recebimento-gas-povo',
    path: '/recebimento-gas-povo',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutRecebimentoValeRoute = LayoutRecebimentoValeRouteImport.update({
  id: '/recebimento-vale',
  path: '/recebimento-vale',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecebimentoValeGasRoute =
  LayoutRecebimentoValeGasRouteImport.update({
    id: '/recebimento-vale-gas',
    path: '/recebimento-vale-gas',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutValeGasRoute = LayoutValeGasRouteImport.update({
  id: '/vale-gas',
  path: '/vale-gas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutValesRoute = LayoutValesRouteImport.update({
  id: '/vales',
  path: '/vales',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutVendasRoute = LayoutVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/abertura-dia': typeof LayoutAberturaDiaRoute
  '/admin': typeof LayoutAdminRoute
  '/chamado': typeof LayoutChamadoRoute
  '/chamados-ativos': typeof LayoutChamadosAtivosRoute
  '/clientes': typeof LayoutClientesRoute
  '/dashboard-saldos': typeof LayoutDashboardSaldosRoute
  '/fechamento-dia': typeof LayoutFechamentoDiaRoute
  '/inadimplentes': typeof LayoutInadimplentesRoute
  '/livro-vendas': typeof LayoutLivroVendasRoute
  '/mapa': typeof LayoutMapaRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/precos': typeof LayoutPrecosRoute
  '/produtos': typeof LayoutProdutosRoute
  '/recebimento-gas-povo': typeof LayoutRecebimentoGasPovoRoute
  '/recebimento-vale': typeof LayoutRecebimentoValeRoute
  '/recebimento-vale-gas': typeof LayoutRecebimentoValeGasRoute
  '/settings': typeof LayoutSettingsRoute
  '/vale-gas': typeof LayoutValeGasRoute
  '/vales': typeof LayoutValesRoute
  '/vendas': typeof LayoutVendasRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/abertura-dia': typeof LayoutAberturaDiaRoute
  '/admin': typeof LayoutAdminRoute
  '/chamado': typeof LayoutChamadoRoute
  '/chamados-ativos': typeof LayoutChamadosAtivosRoute
  '/clientes': typeof LayoutClientesRoute
  '/dashboard-saldos': typeof LayoutDashboardSaldosRoute
  '/fechamento-dia': typeof LayoutFechamentoDiaRoute
  '/inadimplentes': typeof LayoutInadimplentesRoute
  '/livro-vendas': typeof LayoutLivroVendasRoute
  '/mapa': typeof LayoutMapaRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/precos': typeof LayoutPrecosRoute
  '/produtos': typeof LayoutProdutosRoute
  '/recebimento-gas-povo': typeof LayoutRecebimentoGasPovoRoute
  '/recebimento-vale': typeof LayoutRecebimentoValeRoute
  '/recebimento-vale-gas': typeof LayoutRecebimentoValeGasRoute
  '/settings': typeof LayoutSettingsRoute
  '/vale-gas': typeof LayoutValeGasRoute
  '/vales': typeof LayoutValesRoute
  '/vendas': typeof LayoutVendasRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/_layout/abertura-dia': typeof LayoutAberturaDiaRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chamado': typeof LayoutChamadoRoute
  '/_layout/chamados-ativos': typeof LayoutChamadosAtivosRoute
  '/_layout/clientes': typeof LayoutClientesRoute
  '/_layout/dashboard-saldos': typeof LayoutDashboardSaldosRoute
  '/_layout/fechamento-dia': typeof LayoutFechamentoDiaRoute
  '/_layout/inadimplentes': typeof LayoutInadimplentesRoute
  '/_layout/livro-vendas': typeof LayoutLivroVendasRoute
  '/_layout/mapa': typeof LayoutMapaRoute
  '/_layout/permissions': typeof LayoutPermissionsRoute
  '/_layout/precos': typeof LayoutPrecosRoute
  '/_layout/produtos': typeof LayoutProdutosRoute
  '/_layout/recebimento-gas-povo': typeof LayoutRecebimentoGasPovoRoute
  '/_layout/recebimento-vale': typeof LayoutRecebimentoValeRoute
  '/_layout/recebimento-vale-gas': typeof LayoutRecebimentoValeGasRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/vale-gas': typeof LayoutValeGasRoute
  '/_layout/vales': typeof LayoutValesRoute
  '/_layout/vendas': typeof LayoutVendasRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/abertura-dia'
    | '/admin'
    | '/chamado'
    | '/chamados-ativos'
    | '/clientes'
    | '/dashboard-saldos'
    | '/fechamento-dia'
    | '/inadimplentes'
    | '/livro-vendas'
    | '/mapa'
    | '/permissions'
    | '/precos'
    | '/produtos'
    | '/recebimento-gas-povo'
    | '/recebimento-vale'
    | '/recebimento-vale-gas'
    | '/settings'
    | '/vale-gas'
    | '/vales'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/abertura-dia'
    | '/admin'
    | '/chamado'
    | '/chamados-ativos'
    | '/clientes'
    | '/dashboard-saldos'
    | '/fechamento-dia'
    | '/inadimplentes'
    | '/livro-vendas'
    | '/mapa'
    | '/permissions'
    | '/precos'
    | '/produtos'
    | '/recebimento-gas-povo'
    | '/recebimento-vale'
    | '/recebimento-vale-gas'
    | '/settings'
    | '/vale-gas'
    | '/vales'
    | '/vendas'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/_layout/abertura-dia'
    | '/_layout/admin'
    | '/_layout/chamado'
    | '/_layout/chamados-ativos'
    | '/_layout/clientes'
    | '/_layout/dashboard-saldos'
    | '/_layout/fechamento-dia'
    | '/_layout/inadimplentes'
    | '/_layout/livro-vendas'
    | '/_layout/mapa'
    | '/_layout/permissions'
    | '/_layout/precos'
    | '/_layout/produtos'
    | '/_layout/recebimento-gas-povo'
    | '/_layout/recebimento-vale'
    | '/_layout/recebimento-vale-gas'
    | '/_layout/settings'
    | '/_layout/vale-gas'
    | '/_layout/vales'
    | '/_layout/vendas'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupB2cDisabledRoute: typeof SignupB2cDisabledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-b2c-disabled': {
      id: '/signup-b2c-disabled'
      path: '/signup-b2c-disabled'
      fullPath: '/signup-b2c-disabled'
      preLoaderRoute: typeof SignupB2cDisabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/abertura-dia': {
      id: '/_layout/abertura-dia'
      path: '/abertura-dia'
      fullPath: '/abertura-dia'
      preLoaderRoute: typeof LayoutAberturaDiaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chamado': {
      id: '/_layout/chamado'
      path: '/chamado'
      fullPath: '/chamado'
      preLoaderRoute: typeof LayoutChamadoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chamados-ativos': {
      id: '/_layout/chamados-ativos'
      path: '/chamados-ativos'
      fullPath: '/chamados-ativos'
      preLoaderRoute: typeof LayoutChamadosAtivosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes': {
      id: '/_layout/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof LayoutClientesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard-saldos': {
      id: '/_layout/dashboard-saldos'
      path: '/dashboard-saldos'
      fullPath: '/dashboard-saldos'
      preLoaderRoute: typeof LayoutDashboardSaldosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fechamento-dia': {
      id: '/_layout/fechamento-dia'
      path: '/fechamento-dia'
      fullPath: '/fechamento-dia'
      preLoaderRoute: typeof LayoutFechamentoDiaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/inadimplentes': {
      id: '/_layout/inadimplentes'
      path: '/inadimplentes'
      fullPath: '/inadimplentes'
      preLoaderRoute: typeof LayoutInadimplentesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/livro-vendas': {
      id: '/_layout/livro-vendas'
      path: '/livro-vendas'
      fullPath: '/livro-vendas'
      preLoaderRoute: typeof LayoutLivroVendasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mapa': {
      id: '/_layout/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof LayoutMapaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/permissions': {
      id: '/_layout/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof LayoutPermissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/precos': {
      id: '/_layout/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof LayoutPrecosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/produtos': {
      id: '/_layout/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof LayoutProdutosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recebimento-gas-povo': {
      id: '/_layout/recebimento-gas-povo'
      path: '/recebimento-gas-povo'
      fullPath: '/recebimento-gas-povo'
      preLoaderRoute: typeof LayoutRecebimentoGasPovoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recebimento-vale': {
      id: '/_layout/recebimento-vale'
      path: '/recebimento-vale'
      fullPath: '/recebimento-vale'
      preLoaderRoute: typeof LayoutRecebimentoValeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recebimento-vale-gas': {
      id: '/_layout/recebimento-vale-gas'
      path: '/recebimento-vale-gas'
      fullPath: '/recebimento-vale-gas'
      preLoaderRoute: typeof LayoutRecebimentoValeGasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vale-gas': {
      id: '/_layout/vale-gas'
      path: '/vale-gas'
      fullPath: '/vale-gas'
      preLoaderRoute: typeof LayoutValeGasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vales': {
      id: '/_layout/vales'
      path: '/vales'
      fullPath: '/vales'
      preLoaderRoute: typeof LayoutValesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vendas': {
      id: '/_layout/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof LayoutVendasRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAberturaDiaRoute: typeof LayoutAberturaDiaRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChamadoRoute: typeof LayoutChamadoRoute
  LayoutChamadosAtivosRoute: typeof LayoutChamadosAtivosRoute
  LayoutClientesRoute: typeof LayoutClientesRoute
  LayoutDashboardSaldosRoute: typeof LayoutDashboardSaldosRoute
  LayoutFechamentoDiaRoute: typeof LayoutFechamentoDiaRoute
  LayoutInadimplentesRoute: typeof LayoutInadimplentesRoute
  LayoutLivroVendasRoute: typeof LayoutLivroVendasRoute
  LayoutMapaRoute: typeof LayoutMapaRoute
  LayoutPermissionsRoute: typeof LayoutPermissionsRoute
  LayoutPrecosRoute: typeof LayoutPrecosRoute
  LayoutProdutosRoute: typeof LayoutProdutosRoute
  LayoutRecebimentoGasPovoRoute: typeof LayoutRecebimentoGasPovoRoute
  LayoutRecebimentoValeRoute: typeof LayoutRecebimentoValeRoute
  LayoutRecebimentoValeGasRoute: typeof LayoutRecebimentoValeGasRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutValeGasRoute: typeof LayoutValeGasRoute
  LayoutValesRoute: typeof LayoutValesRoute
  LayoutVendasRoute: typeof LayoutVendasRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAberturaDiaRoute: LayoutAberturaDiaRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChamadoRoute: LayoutChamadoRoute,
  LayoutChamadosAtivosRoute: LayoutChamadosAtivosRoute,
  LayoutClientesRoute: LayoutClientesRoute,
  LayoutDashboardSaldosRoute: LayoutDashboardSaldosRoute,
  LayoutFechamentoDiaRoute: LayoutFechamentoDiaRoute,
  LayoutInadimplentesRoute: LayoutInadimplentesRoute,
  LayoutLivroVendasRoute: LayoutLivroVendasRoute,
  LayoutMapaRoute: LayoutMapaRoute,
  LayoutPermissionsRoute: LayoutPermissionsRoute,
  LayoutPrecosRoute: LayoutPrecosRoute,
  LayoutProdutosRoute: LayoutProdutosRoute,
  LayoutRecebimentoGasPovoRoute: LayoutRecebimentoGasPovoRoute,
  LayoutRecebimentoValeRoute: LayoutRecebimentoValeRoute,
  LayoutRecebimentoValeGasRoute: LayoutRecebimentoValeGasRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutValeGasRoute: LayoutValeGasRoute,
  LayoutValesRoute: LayoutValesRoute,
  LayoutVendasRoute: LayoutVendasRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupB2cDisabledRoute: SignupB2cDisabledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
