/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupB2cDisabledRouteImport } from './routes/signup-b2c-disabled'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutClientesRouteImport } from './routes/_layout/clientes'
import { Route as LayoutPermissionsRouteImport } from './routes/_layout/permissions'
import { Route as LayoutPrecosRouteImport } from './routes/_layout/precos'
import { Route as LayoutProdutosRouteImport } from './routes/_layout/produtos'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutValesRouteImport } from './routes/_layout/vales'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupB2cDisabledRoute = SignupB2cDisabledRouteImport.update({
  id: '/signup-b2c-disabled',
  path: '/signup-b2c-disabled',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientesRoute = LayoutClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPermissionsRoute = LayoutPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrecosRoute = LayoutPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProdutosRoute = LayoutProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutValesRoute = LayoutValesRouteImport.update({
  id: '/vales',
  path: '/vales',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/admin': typeof LayoutAdminRoute
  '/clientes': typeof LayoutClientesRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/precos': typeof LayoutPrecosRoute
  '/produtos': typeof LayoutProdutosRoute
  '/settings': typeof LayoutSettingsRoute
  '/vales': typeof LayoutValesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/admin': typeof LayoutAdminRoute
  '/clientes': typeof LayoutClientesRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/precos': typeof LayoutPrecosRoute
  '/produtos': typeof LayoutProdutosRoute
  '/settings': typeof LayoutSettingsRoute
  '/vales': typeof LayoutValesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup-b2c-disabled': typeof SignupB2cDisabledRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/clientes': typeof LayoutClientesRoute
  '/_layout/permissions': typeof LayoutPermissionsRoute
  '/_layout/precos': typeof LayoutPrecosRoute
  '/_layout/produtos': typeof LayoutProdutosRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/vales': typeof LayoutValesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/admin'
    | '/clientes'
    | '/permissions'
    | '/precos'
    | '/produtos'
    | '/settings'
    | '/vales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/admin'
    | '/clientes'
    | '/permissions'
    | '/precos'
    | '/produtos'
    | '/settings'
    | '/vales'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup-b2c-disabled'
    | '/_layout/admin'
    | '/_layout/clientes'
    | '/_layout/permissions'
    | '/_layout/precos'
    | '/_layout/produtos'
    | '/_layout/settings'
    | '/_layout/vales'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupB2cDisabledRoute: typeof SignupB2cDisabledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-b2c-disabled': {
      id: '/signup-b2c-disabled'
      path: '/signup-b2c-disabled'
      fullPath: '/signup-b2c-disabled'
      preLoaderRoute: typeof SignupB2cDisabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clientes': {
      id: '/_layout/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof LayoutClientesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/permissions': {
      id: '/_layout/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof LayoutPermissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/precos': {
      id: '/_layout/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof LayoutPrecosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/produtos': {
      id: '/_layout/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof LayoutProdutosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/vales': {
      id: '/_layout/vales'
      path: '/vales'
      fullPath: '/vales'
      preLoaderRoute: typeof LayoutValesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutClientesRoute: typeof LayoutClientesRoute
  LayoutPermissionsRoute: typeof LayoutPermissionsRoute
  LayoutPrecosRoute: typeof LayoutPrecosRoute
  LayoutProdutosRoute: typeof LayoutProdutosRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutValesRoute: typeof LayoutValesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutClientesRoute: LayoutClientesRoute,
  LayoutPermissionsRoute: LayoutPermissionsRoute,
  LayoutPrecosRoute: LayoutPrecosRoute,
  LayoutProdutosRoute: LayoutProdutosRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutValesRoute: LayoutValesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupB2cDisabledRoute: SignupB2cDisabledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
